@host = http://localhost:3000
@tokenPepe = eyJhbGciOiJIUzI1NiJ9.UGVwZQ.Sqoz9-3DcqpMYBWcSX7X4BJ4_Xwhm-Li_lnUe6RD9cY
@tokenLaura = eyJhbGciOiJIUzI1NiJ9.TGF1cmE.5lN2UMvvfYIDYiiF3MrqNLgeoMVmEdlCP1WOR-LoarE


### REQUEST USERS

### Registrar nuevo usuario
###
POST {{host}}/api/users/register
Content-Type: application/json


{
    "username": "Lucía",
    "password": "2525"
}


### Login de usuario 
###
POST {{host}}/api/users/login
Content-Type: application/json

{
    "username": "Lucía",
    "password": "2525"
}


### Obtener perfil de usuario
###
GET {{host}}/api/users/profile
Authorization: eyJhbGciOiJIUzI1NiJ9.THVjw61h.JGq1x4tEkB1YiKsuHFmZ7H7g1QxZDzHZAfFGOQ5gQmw




### REQUEST EVENTS

### Obtener todos los eventos
###
GET {{host}}/api/events
Authorization: {{tokenLaura}}



### Obtener evento por id
###
GET {{host}}/api/events/58
Authorization: {{tokenLaura}}



### Obtener eventos por fecha
###
GET {{host}}/api/events/upcoming
Authorization: {{tokenLaura}}



### Obtener por tipos de deporte
###
GET {{host}}/api/events?tipoDeporte=Fútbol
Authorization: {{tokenLaura}}


### Obtener eventos por fecha
###
GET {{host}}/api/events/date?from=2025-05-02&to=2025-09-20
Authorization: {{tokenLaura}}


TODO
//Obtener eventos por página



### Crear nuevo evento
###
POST {{host}}/api/events
Authorization: {{tokenPepe}}
Content-Type: application/json

{
    "nombre": "Partido de fútbol sala",
    "descripcion": "Campeonato de fútbol entre los equipos de la liga",
    "fecha": "2025-05-02",
    "ubicacion": "Madrid",
    "tipoDeporte": "Fútbol",
    "organizador": "Ramon"
}



### Actualizar evento
###
PUT {{host}}/api/events/45
Authorization: {{tokenPepe}}
Content-Type: application/json

{
    "nombre": "Campeonato Fútbol Sala",
    "descripcion": "Semifinal del campeonato regional de fútbol sala",
    "fecha": "2025-8-5",
    "ubicacion": "Burgos",
    "tipoDeporte": "Fútbol"
}


### Borrar un evento
DELETE {{host}}/api/events/44
Authorization: eyJhbGciOiJIUzI1NiJ9.THVjw61h.JGq1x4tEkB1YiKsuHFmZ7H7g1QxZDzHZAfFGOQ5gQmw


