@host = http://localhost:3000

### REQUEST EVENTS

### Obtener todos los eventos
###
GET {{host}}/api/events

### Obtener evento por id
###
GET {{host}}/api/events/25

### Crear nuevo evento
###
POST {{host}}/api/events
Content-Type: application/json

{
    "nombre": "Carrera infantil 2km",
    "descripcion": "Carrera de 2kms para niños menores de 16 años.",
    "fecha": "2025-10-14",
    "ubicacion": "Jaén",
    "tipoDeporte": "Atletismo"
}

### Actualizar evento
###
PUT {{host}}/api/events/41
Content-Type: application/json

{
    "nombre": "Campeonato Fútbol Sala",
    "descripcion": "Semifinal del campeonato regional de fútbol sala",
    "fecha": "2025-8-5",
    "ubicacion": "Burgos",
    "tipoDeporte": "Fútbol"
}


### Borrar un evento
DELETE {{host}}/api/events/41


### Obtener eventos por fecha
###
GET {{host}}/api/events/upcoming


### Obtener por tipos de deporte
###
GET {{host}}/api/events/sports?type=Atletismo


// TODO: GET /api/events/date?from=2023-09-10&to=2023-09-20: Devuelve los eventos dentro del rango de fechas especificado.





### REQUEST USERS

###
POST {{host}}/api/users/register
Content-Type: application/json

{
    "username": "Noelia",
    "password": "1234"
}
